### ISSUE TITLE
TypeError in VorwerkState

### ISSUE THREAD

**Issue by marecabo** [trunneml/homeassistant-vorwerk#1]
First, great thanks for working on this integration!

I am experiencing this error when using it with my VR300

```python
2021-05-15 11:22:18 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/workspaces/home-assistant-core/homeassistant/helpers/update_coordinator.py", line 130, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/workspaces/home-assistant-core/homeassistant/helpers/update_coordinator.py", line 262, in _async_refresh
    update_callback()
  File "/workspaces/home-assistant-core/homeassistant/helpers/update_coordinator.py", line 322, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/workspaces/home-assistant-core/homeassistant/helpers/entity.py", line 350, in async_write_ha_state
    self._async_write_ha_state()
  File "/workspaces/home-assistant-core/homeassistant/helpers/entity.py", line 384, in _async_write_ha_state
    state = self._stringify_state()
  File "/workspaces/home-assistant-core/homeassistant/helpers/entity.py", line 356, in _stringify_state
    state = self.state
  File "/workspaces/home-assistant-core/homeassistant/components/vorwerk/vacuum.py", line 131, in state
    return self._state.state if self._state else None
  File "/workspaces/home-assistant-core/homeassistant/components/vorwerk/api.py", line 123, in state
    if robot_state["action"] != ROBOT_ACTION_DOCKING:
TypeError: 'int' object is not subscriptable
```

It seems a bit odd to me to attempt to access a key of a dict when comparing for equality with an int in the previous line. https://github.com/trunneml/homeassistant-vorwerk/blob/6af13731e89eca98583f1a3827c130d1369f407d/api.py#L120-L124
Did that really work for your robot?

- Home Assistant 2021.6.0-dev
- Vorwerk VR300 @ 4.6.1-102

**Comment by trunneml** [comment]
Thanks, for your help. Could you try it again?

**Comment by marecabo** [comment]
Thanks, ~~this one seems fine~~, I discovered another weird behavior here: https://github.com/trunneml/homeassistant-vorwerk/issues/1#issuecomment-841683539

There is another one popping up in https://github.com/trunneml/homeassistant-vorwerk/blob/12e693c3ffe4e6052665bea84536285f42399165/__init__.py#L290

```python
2021-05-15 15:34:36 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/workspaces/home-assistant-core/homeassistant/helpers/update_coordinator.py", line 130, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/workspaces/home-assistant-core/homeassistant/helpers/update_coordinator.py", line 262, in _async_refresh
    update_callback()
  File "/workspaces/home-assistant-core/homeassistant/helpers/update_coordinator.py", line 322, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/workspaces/home-assistant-core/homeassistant/helpers/entity.py", line 350, in async_write_ha_state
    self._async_write_ha_state()
  File "/workspaces/home-assistant-core/homeassistant/helpers/entity.py", line 391, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/workspaces/home-assistant-core/homeassistant/components/vorwerk/vacuum.py", line 143, in device_state_attributes
    if self._state.status is not None:
  File "/workspaces/home-assistant-core/homeassistant/components/vorwerk/api.py", line 211, in status
    status = self._cleaning_status()
  File "/workspaces/home-assistant-core/homeassistant/components/vorwerk/api.py", line 226, in _cleaning_status
    MODE.get(robot_state["cleaning"]["mode"]),
TypeError: 'int' object is not subscriptable
```

**Comment by marecabo** [comment]
And in https://github.com/trunneml/homeassistant-vorwerk/blob/12e693c3ffe4e6052665bea84536285f42399165/__init__.py#L265-L279 is it meant to be without these lines?

```python
        elif self.state == STATE_RETURNING:
            status = "Returning"
```

**Comment by marecabo** [comment]
> Thanks, for your help. Could you try it again?

Okay, I just observed a weird behavior at https://github.com/trunneml/homeassistant-vorwerk/blob/12e693c3ffe4e6052665bea84536285f42399165/__init__.py#L238-L242

When I used the zone cleaning feature from the app, the action is 11 (Map Cleaning) and the robot device showed "Returning" as state for the whole cleaning procedure.

I think, this would be a more robust condition:
```python
        elif robot_state == ROBOT_STATE_BUSY:
            action = self.robot_state.get("action")
            if action not in [
                ROBOT_ACTION_HOUSE_CLEANING,
                ROBOT_ACTION_SPOT_CLEANING,
                ROBOT_ACTION_MANUAL_CLEANING,
                ROBOT_ACTION_MAP_CLEANING,
                ROBOT_ACTION_MAP_EXPLORING
            ]:
                state = STATE_RETURNING
            else:
                state = STATE_CLEANING
```

**Comment by trunneml** [comment]
Agree, my VR200 has no zone cleaning support.

**Comment by trunneml** [comment]
Should be working now. Could you check it with your VR300?

**Comment by marecabo** [comment]
Will do right away.

**Comment by marecabo** [comment]
~~Okay, first, it looks like there are some missing modifications from when refactoring the `api.py` file in~~ 
- ~~https://github.com/trunneml/homeassistant-vorwerk/blob/main/switch.py#L14~~
- ~~https://github.com/trunneml/homeassistant-vorwerk/blob/main/sensor.py#L14~~

Nevermind, you were 20 s faster ;)

**Comment by trunneml** [comment]
> 
> 
> Okay, first, it looks like there are some missing modifications from when refactoring the `api.py` file in
> 
>     * https://github.com/trunneml/homeassistant-vorwerk/blob/main/switch.py#L14
> 
>     * https://github.com/trunneml/homeassistant-vorwerk/blob/main/sensor.py#L14
 
Already fixed that with fa0007420e78efb2ca82d01957cf6ad04bccd209 :)

**Comment by trunneml** [comment]
> 
> 
> ~Okay, first, it looks like there are some missing modifications from when refactoring the `api.py` file in~
> 
>     * ~https://github.com/trunneml/homeassistant-vorwerk/blob/main/switch.py#L14~
> 
>     * ~https://github.com/trunneml/homeassistant-vorwerk/blob/main/sensor.py#L14~
> 
> 
> Nevermind, you were 20 s faster ;)

The homeassistant review team didn't like that module. I'm trying to keep this repository and the official PR in sync. But that makes some serious problems.

**Comment by marecabo** [comment]
You mean, that they insist on having a first pr with only the vacuum platform? I think, removing the sensor and switch for the first pr and making subsequent ones with sensor and switch should be doable, or not?

**Comment by trunneml** [comment]
My VR200 just show docked now instead of cleaning. :(
But return to dock is now correct. :)

**Comment by marecabo** [comment]
Hmm, can you debug and set a breakpoint in https://github.com/trunneml/homeassistant-vorwerk/blob/main/__init__.py#L247 to check the actual value of its action? This is how I discovered the other cleaning values.

**Comment by trunneml** [comment]
> 
> 
> You mean, that they insist on having a first pr with only the vacuum platform? I think, removing the sensor and switch for the first pr and making subsequent ones with sensor and switch should be doable, or not?

It is.

**Comment by trunneml** [comment]
> 
> 
> Hmm, can you debug and set a breakpoint in https://github.com/trunneml/homeassistant-vorwerk/blob/main/__init__.py#L247 to check the actual value of its action? This is how I discovered the other cleaning values.

I don't know how to remote debug hassio on a raspberry pi with breakpoints. But I will add some logging here.

**Comment by marecabo** [comment]
I admit, I also never debugged my production instance, but I would try it with [debugpy](https://www.home-assistant.io/integrations/debugpy/).

Edit: I got it to work, from opening VS Code on a cloned home-assistant/core repo and selecting "Home Assistant: Attach Remote" as debug config. However, I have integrated your component in the home-assistant/core repo here for development: https://github.com/marecabo/home-assistant-core/tree/trunneml-vorwerk-hacs

**Comment by trunneml** [comment]
Found the problem. The status_message had the same problem and did throw an exception. So the state was not updated.

This version works on my VR200 could you try it on with your VR300 please? :)

**Comment by marecabo** [comment]
Cool, can you point me at the changes you made, so I can integrate them in my dev environment?

**Comment by trunneml** [comment]
> 
> 
> Cool, can you point me at the changes you made, so I can integrate them in my dev environment?
 I squashed every thing into: 34669f5

I did a history clean up in the main branch so just read the git log :)

**Comment by marecabo** [comment]
oh, yeah the commits are squashed, no worries

**Comment by marecabo** [comment]
But I would still recommend to add `ROBOT_ACTION_EXPLORING_MAP` to the `ROBOT_CLEANING_ACTIONS` as the robot is cleaning while exploring.

**Comment by trunneml** [comment]
Wait a second i will add it and squash it again

**Comment by marecabo** [comment]
Maybe you could also look at this https://github.com/trunneml/homeassistant-vorwerk/issues/1#issuecomment-841682540? I'm not sure, if it's missing some lines there?

**Comment by trunneml** [comment]
> 
> 
> Maybe you could also look at this [#1 (comment)](https://github.com/trunneml/homeassistant-vorwerk/issues/1#issuecomment-841682540)? I'm not sure, if it's missing some lines there?

That status thing is from the old neato integration. It just adds an attribute to the entity, not more. 
In my opinion the important things are error status and cleaning status. 
I will refactor this in the next step.

**Comment by marecabo** [comment]
I agree, the error and alert status should have the highest priority, the rest is just a repetition of the state.

I think, the current mode and current zone from the cleaning status should better be seperate attributes that are only present when the robot is actually cleaning.

**Comment by trunneml** [comment]
Agree. I will refactor this in the next step, depending on the Homeassistant PR feedback.
In the mean while I added the returning as suggested.

Could you check it and close the ticket, when it's working on the VR300?

**Comment by marecabo** [comment]
Looks good so far, I do not have any more errors in the logs. Thanks for your time! 👍
