### ISSUE TITLE
No reconnect or refresh?

### ISSUE THREAD

**Issue by SkylightXD** [trunneml/homeassistant-vorwerk#10]
One of my robots was emtpy, so that this integration can not communicate with the robot.
So the integration goes into an error state. But now all robots are fine and I see them in the app, but the integration stays in this error ...
If I delete the integration and setup new, than everything is fine ...

Could you help me? 
Is there any reconnect, refresh or reintialation? 

Thanks and regards! :)

**Comment by trunneml** [comment]
I will check how to trigger a reconfiguration when a defect configuration is detected. Shot question how did you managed to get an empty robot config?
