### ISSUE TITLE
Warnings associated with HA beta release 2021.12.0b0

### ISSUE THREAD

**Issue by grantclem** [trunneml/homeassistant-vorwerk#11]
Warnings after install of latest beta 2012.12.b0

https://rc.home-assistant.io/blog/2021/12/03/release-202112/#updates-for-custom-integration-developers

`2021-12-04 08:29:05 WARNING (MainThread) [homeassistant.helpers.entity] Entity vacuum.robot_vac (<class 'custom_components.vorwerk.vacuum.VorwerkConnectedVacuum'>) implements device_state_attributes. Please report it to the custom component author.`

**Comment by trunneml** [comment]
Thanks, I created a patch for it.
