### ISSUE TITLE
No function with 0.9.4

### ISSUE THREAD

**Issue by Friedi1970** [trunneml/homeassistant-vorwerk#14]
Since this last update there is no functionality on my VR200.
The sensors are all OK but there is no action on my automations. Even when I hit the start cleaning at the device in HA there is no action.
Before the last update everything worked well and now the is no cleaning :(

**Comment by trunneml** [comment]
Yeah #4 hits again. I copied changes some changes from neato and lost my fix.

**Comment by trunneml** [comment]
Should be fixed with 0.9.5

**Comment by Friedi1970** [comment]
> Should be fixed with 0.9.5

Nope. It still doesn‘t work. With 0.9.3 it still works …

**Comment by trunneml** [comment]
Yepp, that patch was screwed. Could you please try main.

**Comment by Friedi1970** [comment]
I installed the latest version and it doesn‘t work.
What main shall I try?

**Comment by trunneml** [comment]
main is the branch. But I will create a release for you. :)

**Comment by trunneml** [comment]
Please try 0.9.6
