### ISSUE TITLE
Vacuum entity has no device info

### ISSUE THREAD

**Issue by marecabo** [trunneml/homeassistant-vorwerk#2]
The vacuum entity is not associated with the device as its device info is never retrieved.

https://github.com/trunneml/homeassistant-vorwerk/blob/6af13731e89eca98583f1a3827c130d1369f407d/api.py#L71-L76
`if self.robot_info is None:` will never yield True, as `self.robot_info` is initialized with an empty dict in https://github.com/trunneml/homeassistant-vorwerk/blob/6af13731e89eca98583f1a3827c130d1369f407d/api.py#L58 which is not equal to `None`.

I'd suggest:

```python
        try:
            if not self.robot_info:
                self.robot_info = self.robot.get_general_info().json().get("data")
```

**Comment by trunneml** [comment]
Thanks! Should be fixed now.
