### ISSUE TITLE
Not available in HACS

### ISSUE THREAD

**Issue by LawF0rge52** [trunneml/homeassistant-vorwerk#20]
Hello trunneml and folks,

I'm trying to install your custome integration (for my VR300). As stated in the readme, it should be possible to install it via HACS but I can't find any related repostitory. Can you please guide me to the repo? I searched with VR300 and Vorwerk but nothing namingly is fitting.
Maybe I'm just a noob and still don't know enough about HA :-) but at least HACS is running.

Any help to point me in the right direction would be more than appreciated.

LawF0rge52

**Comment by trunneml** [comment]
Hi,

I didn't had the time to add it into the official HACS list, as I hoped I could integrate it into Home-Assistant directly. 

Here is the HACS manual:

https://hacs.xyz/docs/faq/custom_repositories/
