### ISSUE TITLE
Unable to communicate with robot

### ISSUE THREAD

**Issue by 10erlosh** [trunneml/homeassistant-vorwerk#21]
Hi!
Just added this integration (0.9.6) and completed the login flow but i can't manage to establish a connection.

```
/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'nucleo.ksecosys.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'nucleo.ksecosys.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2023-02-07 11:21:25.823 ERROR (MainThread) [custom_components.vorwerk] Failed to connect to robots: Unable to communicate with robot
```

Communication via mobile app works.

**Comment by trunneml** [comment]
This error means that the vorwerk-cloud can't connect to your robot. It is not a problem of the intergration, but with the robot wifi-connection. Is your robot connected to the kobold-cloud? Is the myVorwerk-App working?

**Comment by 10erlosh** [comment]
Double checked it: The app is working fine. I will check in the evening if there is a firmware update available for the robot.

**Comment by serramat** [comment]
After updated the robot software I have the same problem with Home Assistant. The app work fine but Home Assistant not connected to the robot. I have VR300 with software version 4.6.4-44

**Comment by serramat** [comment]
After removed and readded the integration my problem is gone

**Comment by mjunold** [comment]
> After removed and readded the integration my problem is gone

Worked for me, too

**Comment by 10erlosh** [comment]
> After removed and readded the integration my problem is gone

Works for me.
