### ISSUE TITLE
Certificate warnings

### ISSUE THREAD

**Issue by tofuSCHNITZEL** [trunneml/homeassistant-vorwerk#23]
Hi,
thanks for creating this integration!
I started getting these errors in the home-assistant log:
`InsecureRequestWarning: Unverified HTTPS request is being made to host 'nucleo.ksecosys.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings`

I tried to bump the pybotvac to version 0.0.24 but it contains an old certificate and so the communication stops entirely...
I created a pull request with the new cert:
https://github.com/stianaske/pybotvac/pull/82
but I wonder if there would be a better way? to just enable the urllib3 cert validation like suggested in the link above?

**Comment by tofuSCHNITZEL** [comment]
I would suggest this:
https://github.com/stianaske/pybotvac/pull/83
is there a reason you added the cert? instead of just setting it to True so requests validates the cert (chain) itself?

**Comment by trunneml** [comment]
No. This was at that point in time the easiest way. If `true` is working, that's the way to go. I close this ticket, because it is related to pybotvac.
