### ISSUE TITLE
VR300 identified as VR220

### ISSUE THREAD

**Issue by fabiankrei** [trunneml/homeassistant-vorwerk#24]
First thanks for your great integration. I tried this one for my VR300. Workflow works fine but at the end my VR300 is identified as VR220. I think that is also the reason why VR300 optimizations from FUEMPEL is not working right?
Any suggestion how to get my robot identified correctly?
Thanks!

**Comment by fabiankrei** [comment]
Also selection of zones is not possible. I just have basic options like "clean", "return to docking station"...

**Comment by baflo** [comment]
VR220 is the internal codename by Vorwerk. This should be correct.

**Comment by trunneml** [comment]
There is no zone support in this integrations, because the auth mechanism in [pybotvac](https://github.com/stianaske/pybotvac) for it doesn't work with home assistant. Also the Name `VR220` is coming from [pybotvac](https://github.com/stianaske/pybotvac) so feel free to open a ticket there. :)

**Comment by fabiankrei** [comment]
Ok thanks, I thought with fork of FUEMPEL it would work…

**Comment by trunneml** [comment]
It will until the access_token is expires. Then you need to refresh the token using the refresh_token. This is not implemented in pybotvac.

**Comment by fabiankrei** [comment]
Ok, but as I created the token freshly I understood it should work at least for a while. But where do I find the different zones in home assistant? I just see three entities: robot, battery and schedule. But even under robot I only see the standard command buttons like start, pause…
