### ISSUE TITLE
Specify zones for cleaning with VR300

### ISSUE THREAD

**Issue by marecabo** [trunneml/homeassistant-vorwerk#3]
Just to let you know, that I'm working on this one.

I already managed to get the map (id|name|image) during the config flow and am saving them in the robot config and alter pass it to the robot state.

**Comment by trunneml** [comment]
Good to know.  When you create a PR I will look at it.

Currently I'm working to get the integration to homeassistant-core. It was based on the neato integartion, but they wanted many refactorings. Now nothing is the same and in the first PR for a new integration only one plattform is allowed. So sensors, switches and camera (for the map) will be added later.
And in the lack of a VR300 I removed the map code.

**Comment by marecabo** [comment]
> And in the lack of a VR300 I removed the map code.

Yeah, I saw that and am bringing it back for the VR300, for sure in a way that it does not break any robot without map functionality.

- The map ids can only be accessed from the pybotvac `Account` class which requires a valid session. 
- When the map id is known, a robot object on its own can request a list of boundary ids (zones) to allow for zone cleaning.

So far the session object only lives throughout the config flow phase. Currently I'm retrieving the persistent map ids/names at that phase and save them in the config entry, but this does not allow to get updated map ids without removing and re-adding the integration.

For future features like latest cleaning map image retrieval, there is no way around having an Account object available.

**Comment by baflo** [comment]
How's it going? If any support is needed I could jump in for developing and/or testing.

**Comment by trunneml** [comment]
I'm still waiting that my PR (https://github.com/home-assistant/core/pull/45749) is getting merged.

**Comment by Gruby71** [comment]
It would be great to get the map cleaning available in HomeAssistant. Maybe the the plugin for FHEM can give you a hint how it could work: https://github.com/fhem/BOTVAC 
With FHEM it was working fine with my VR300

**Comment by ncanbr** [comment]
What is the timeframe for getting this available in the custom component?

**Comment by trunneml** [comment]
I have no timeframe. My plan was to get this custom component integrated into home assistant, to bring back the vorwerk support. But my PR doesn't make any progress last year. 
My VR200 does not support this feature, so feel free to fork it and/or create a PR :)

**Comment by Jan022** [comment]
What does it mean “without map sensors” does it mean that the robot ignore all “no go lines” ?

**Comment by trunneml** [comment]
> What does it mean “without map sensors” does it mean that the robot ignore all “no go lines” ?

No, the this logic is in our robot and the vorwerk-cloud.
The map sensor is just a picture that shows a map of our home. 
The information for this sensor is in a part of the vorwerk-cloud where the access logic in pybotvac (the underlying lib of this integration) is broken.

**Comment by Jan022** [comment]
Thanks for this explanation! That’s enough for me!

**Comment by Jan022** [comment]
So I try the add on a few times. Unfortunately the vr300 ignores the no go lines :( 
Do you have an idea why? If I use the original app the robot only clean the correct areas.

**Comment by trunneml** [comment]
> So I try the add on a few times. Unfortunately the vr300 ignores the no go lines :( Do you have an idea why? If I use the original app the robot only clean the correct areas.

Sorry no. I don't own a VR300 only a VR200. What do you mean with No-Go lines? Areas he should never clean like a carpet? That should work because that is not part of the Vorwerk API. But if you mean your robot should this time only clean a specific zone like the living room and skip the floor, that is not working. For that feature we need the zone map but that is not possible because of an authentication issue in `pybotvac`.

**Comment by Gruby71** [comment]
Hi together...
just as a note... the fork from Fuempel (https://github.com/Fuempel) works fine with zones on my VR300. I have not worked with "no-go lines" for now, but you can give it a try with it. 
best regards

**Comment by trunneml** [comment]
@Gruby71 Nice work. But how do you refresh the token when it expires? There is no refresh logic in `pybotvac` for the Vorwerk endpoint?

**Comment by Gruby71** [comment]
@trunneml ... I'm not the developer of that fork, just a user... so... Sorry can't answer that in detail.

**Comment by trunneml** [comment]
Okay, thanks. I didn't find any update logic in the code. So it will work until the token expires and than a reconnect of the robot is needed, which could create some trouble in HA when the robot gets a new entry_id.

**Comment by Gruby71** [comment]
That fit's to my expirience... with the last Firmware update I have had the need to delete the integration and to run the setup again... Before the firmware update for my VR300 it worked fine for a long time.

**Comment by Jan022** [comment]
> > So I try the add on a few times. Unfortunately the vr300 ignores the no go lines :( Do you have an idea why? If I use the original app the robot only clean the correct areas.
> 
> Sorry no. I don't own a VR300 only a VR200. What do you mean with No-Go lines? Areas he should never clean like a carpet? That should work because that is not part of the Vorwerk API. But if you mean your robot should this time only clean a specific zone like the living room and skip the floor, that is not working. For that feature we need the zone map but that is not possible because of an authentication issue in `pybotvac`.

yes the robot „eat“ my carpet. 
The VR300 has a little bit strange behavior, ist you start the robot with the original APP he respects the no go lines/areas. But if you use the button on the robot it self, he don’t respects the no go lines. 
Is it possible that the plug-in “push” the button on the robot and not use the software button?

**Comment by malkie-hass** [comment]
Hey,
I‘m having the same issue with the nogo lines. I had a chat with Vorwerk. If you either press the  green button on the device or the normal start button in the app it will ignore the nogo lines. Only if you start via the app schedule or under the map the cleaning it uses them.
Seems to be a quite stupid behavior but I guess that explains the issue with this integration. It just sends the start command which means nogo lines are ignored.
Would be great to get this somehow.

nogo lines can be set in the map for the vacuum which it is not allowed to pass. So you can spare out some areas it’s not supposed to go to.

Malkie

**Comment by TAOGde** [comment]
Any news about the new VR7? Would be great that the normal states are seen in Homeassistant

**Comment by trunneml** [comment]
No I don't own a VR7 and without it I can't test it. My VR200 was replaced some days ago. So I can't implement the map feature because of the missing hardware.
