### ISSUE TITLE
Vacuum won't start when docked :(

### ISSUE THREAD

**Issue by Friedi1970** [trunneml/homeassistant-vorwerk#4]
I integrated your fine work but unfortunately it doesn't work with my VR200
The only thing what works correctly is the battery status.

When I use "clean" in an automation nothing happens as well when I use the switch to activate the schedule. I the second case the switch shows schedule is on but it isn't on the VR200.

**Comment by trunneml** [comment]
Interessting. Battery status and cleaning uses the same api and credentials. 
Did you try to start the robot via an entity card in lovelace?
![Bildschirmfoto 2021-05-26 um 11 07 13](https://user-images.githubusercontent.com/241487/119633994-9301f580-be12-11eb-8c25-99f80dc98f55.png)

Are there  errors in the log (Configuration > Logs) ?

**Comment by Friedi1970** [comment]
Well, it is getting more weird now ;)

The thing is, I tried it via Lovelace (of course) but nothing happened. No errors in log. But now I had a look to the history:
![image](https://user-images.githubusercontent.com/47818803/119638656-29381a80-be17-11eb-91b9-87471b173569.png)

Every little thing had been logged.

So it seems basically the integration works but no command works.

Regards
Marco

**Comment by trunneml** [comment]
Sorry, what do you mean with "no command"? Can you control the robot with your smartphone app?
Could you increase the log level and post the log of a start here?

**Comment by Friedi1970** [comment]
> what do you mean with "no command"

I mean neither an action from automations nor from love lace. Nothing happens.

> Can you control the robot with your smartphone app?

Yes it works fine.

> Could you increase the log level and post the log of a start here?

This is the only thing I have:
Logger: pybotvac.robot
Source: /usr/local/lib/python3.8/site-packages/pybotvac/robot.py:190
First occurred: 11:48:28 (3 occurrences)
Last logged: 11:48:59

Invalid response from https://nucleo.ksecosys.com/vendors/vorwerk/robots/4S4Z1MWP-38D2698349CA/messages: required key not provided @ data['state']. Got: {'version': 1, 'reqId': '1', 'result': 'ko', 'error': 'ui_alert_invalid'}

**Comment by trunneml** [comment]
Could you try spot cleaning via Lovelace, please?
![Bildschirmfoto 2021-05-26 um 11 56 11](https://user-images.githubusercontent.com/241487/119640928-63a2b700-be19-11eb-88df-123010734dd7.png)

**Comment by Friedi1970** [comment]
This is strange. I reloaded the integration. No the actions are being accepted ...

**Comment by trunneml** [comment]
Hmm, I think there is some problem with the remote API. Currently with myVR only Spot and custom cleaning is working. I will look at it.
Thanks for reporting.

**Comment by Friedi1970** [comment]
Welcome 🙏 
But I think I have to thank you!!!

**Comment by trunneml** [comment]
I think I fixed the problem. You can try the dev branch.

**Comment by trunneml** [comment]
I merged the bug fix into main. Should be working now. If there the problem still exists, please reopen this ticket :)
