### ISSUE TITLE
Status of switch.kobold_schedule doesn‘t change

### ISSUE THREAD

**Issue by Friedi1970** [trunneml/homeassistant-vorwerk#6]
Sorry for finding again an issue ^^

I have an automation to switch off the schedule of my VR200 in case of a calendar entry. Well, the automation is working well and when I habe a look to the Vorwerk App the schedule is switched off. 
The only thing is, the switch.kobold_schedule in HA is still on …

**Comment by trunneml** [comment]
The status is only synced once every minute. Could you test if the status updates after this time, please?

**Comment by Friedi1970** [comment]
Well, it’s hours meanwhile ;)

**Comment by trunneml** [comment]
Okay I will look at it. Personally I don't use the Vorwerk schedule. I trigger the vacuum with a time based automatisation. 🙃

**Comment by trunneml** [comment]
Could you try the kobold_schedule branch? It should be working there.

**Comment by trunneml** [comment]
I think it is working now. If there is still a problem just reopen the ticket.

**Comment by Friedi1970** [comment]
> Could you try the kobold_schedule branch? It should be working there.

It works perfect 👍 Thanks 🙏
